/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppAboutus {
    }
    interface AppBlog {
    }
    interface AppContactus {
        "name6": string;
    }
    interface AppDonate {
        "name5": string;
    }
    interface AppHome {
    }
    interface AppIndex {
    }
    interface AppPortfolio {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppProjects {
        "name3": string;
    }
    interface AppReg {
        "name4": string;
    }
    interface AppRoot {
    }
    interface AppServices {
    }
    interface TestPage {
    }
}
declare global {
    interface HTMLAppAboutusElement extends Components.AppAboutus, HTMLStencilElement {
    }
    var HTMLAppAboutusElement: {
        prototype: HTMLAppAboutusElement;
        new (): HTMLAppAboutusElement;
    };
    interface HTMLAppBlogElement extends Components.AppBlog, HTMLStencilElement {
    }
    var HTMLAppBlogElement: {
        prototype: HTMLAppBlogElement;
        new (): HTMLAppBlogElement;
    };
    interface HTMLAppContactusElement extends Components.AppContactus, HTMLStencilElement {
    }
    var HTMLAppContactusElement: {
        prototype: HTMLAppContactusElement;
        new (): HTMLAppContactusElement;
    };
    interface HTMLAppDonateElement extends Components.AppDonate, HTMLStencilElement {
    }
    var HTMLAppDonateElement: {
        prototype: HTMLAppDonateElement;
        new (): HTMLAppDonateElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppIndexElement extends Components.AppIndex, HTMLStencilElement {
    }
    var HTMLAppIndexElement: {
        prototype: HTMLAppIndexElement;
        new (): HTMLAppIndexElement;
    };
    interface HTMLAppPortfolioElement extends Components.AppPortfolio, HTMLStencilElement {
    }
    var HTMLAppPortfolioElement: {
        prototype: HTMLAppPortfolioElement;
        new (): HTMLAppPortfolioElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppProjectsElement extends Components.AppProjects, HTMLStencilElement {
    }
    var HTMLAppProjectsElement: {
        prototype: HTMLAppProjectsElement;
        new (): HTMLAppProjectsElement;
    };
    interface HTMLAppRegElement extends Components.AppReg, HTMLStencilElement {
    }
    var HTMLAppRegElement: {
        prototype: HTMLAppRegElement;
        new (): HTMLAppRegElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppServicesElement extends Components.AppServices, HTMLStencilElement {
    }
    var HTMLAppServicesElement: {
        prototype: HTMLAppServicesElement;
        new (): HTMLAppServicesElement;
    };
    interface HTMLTestPageElement extends Components.TestPage, HTMLStencilElement {
    }
    var HTMLTestPageElement: {
        prototype: HTMLTestPageElement;
        new (): HTMLTestPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-aboutus": HTMLAppAboutusElement;
        "app-blog": HTMLAppBlogElement;
        "app-contactus": HTMLAppContactusElement;
        "app-donate": HTMLAppDonateElement;
        "app-home": HTMLAppHomeElement;
        "app-index": HTMLAppIndexElement;
        "app-portfolio": HTMLAppPortfolioElement;
        "app-profile": HTMLAppProfileElement;
        "app-projects": HTMLAppProjectsElement;
        "app-reg": HTMLAppRegElement;
        "app-root": HTMLAppRootElement;
        "app-services": HTMLAppServicesElement;
        "test-page": HTMLTestPageElement;
    }
}
declare namespace LocalJSX {
    interface AppAboutus {
    }
    interface AppBlog {
    }
    interface AppContactus {
        "name6"?: string;
    }
    interface AppDonate {
        "name5"?: string;
    }
    interface AppHome {
    }
    interface AppIndex {
    }
    interface AppPortfolio {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppProjects {
        "name3"?: string;
    }
    interface AppReg {
        "name4"?: string;
    }
    interface AppRoot {
    }
    interface AppServices {
    }
    interface TestPage {
    }
    interface IntrinsicElements {
        "app-aboutus": AppAboutus;
        "app-blog": AppBlog;
        "app-contactus": AppContactus;
        "app-donate": AppDonate;
        "app-home": AppHome;
        "app-index": AppIndex;
        "app-portfolio": AppPortfolio;
        "app-profile": AppProfile;
        "app-projects": AppProjects;
        "app-reg": AppReg;
        "app-root": AppRoot;
        "app-services": AppServices;
        "test-page": TestPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-aboutus": LocalJSX.AppAboutus & JSXBase.HTMLAttributes<HTMLAppAboutusElement>;
            "app-blog": LocalJSX.AppBlog & JSXBase.HTMLAttributes<HTMLAppBlogElement>;
            "app-contactus": LocalJSX.AppContactus & JSXBase.HTMLAttributes<HTMLAppContactusElement>;
            "app-donate": LocalJSX.AppDonate & JSXBase.HTMLAttributes<HTMLAppDonateElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-index": LocalJSX.AppIndex & JSXBase.HTMLAttributes<HTMLAppIndexElement>;
            "app-portfolio": LocalJSX.AppPortfolio & JSXBase.HTMLAttributes<HTMLAppPortfolioElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-projects": LocalJSX.AppProjects & JSXBase.HTMLAttributes<HTMLAppProjectsElement>;
            "app-reg": LocalJSX.AppReg & JSXBase.HTMLAttributes<HTMLAppRegElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-services": LocalJSX.AppServices & JSXBase.HTMLAttributes<HTMLAppServicesElement>;
            "test-page": LocalJSX.TestPage & JSXBase.HTMLAttributes<HTMLTestPageElement>;
        }
    }
}
